export const CATEGORIES = [
  { id: 1, name: "All Projects", value: "projects" },
  { id: 2, name: "Architecture", value: "architecture" },
  { id: 3, name: "Interior Design", value: "interior" },
  { id: 4, name: "Urban Design", value: "urban" },
  { id: 5, name: "Products", value: "products" },
];
export const SUB_CATEGORIES = [
  "Residential",
  "Commercial",
  "Institutional",
  "Hospitality",
];
export const WORK_DATA = [
  {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Mansion, New York",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Haven, Sydney",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Opal Oasis, Rio de Janeiro",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Citrine Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },

  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img4.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img2.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Diamond Mall, Shanghai",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Granite Library, Sydney",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Crystal Cafe, Paris",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Quartz Residences, New York",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Gold Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Marble Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Apartments, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Sapphire Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Opal Office, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Sapphire Villa, Paris",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Mansion, New York",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Ruby Retreat, Tokyo",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Topaz Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Haven, Sydney",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Opal Oasis, Rio de Janeiro",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Quartz Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Pearl Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Jade Junction, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Citrine Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Garnet Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Amethyst Alley, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Azure Apartments, Madrid",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img2.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Diamond Mall, Shanghai",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img1.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Granite Library, Sydney",
    links: "./project.html",
    category: "architecture",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Crystal Cafe, Paris",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Quartz Residences, New York",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Gold Tower, Dubai",
    links: "./project.html",
    category: "interior",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Marble Plaza, Singapore",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Ruby Park, London",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Amber Apartments, Beijing",
    links: "./project.html",
    category: "urban",
    imgSrc: "./media//work-img1.jpg",
    type: "residential",
  },
  {
    year: 2016,
    name: "Sapphire Center, Mumbai",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img2.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "architecture",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "institutional",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "commercial",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "architecture",
  },
  {
    year: 2016,
    name: "Emerald Gardens, Cape Town",
    links: "./project.html",
    category: "products",
    imgSrc: "./media//work-img3.jpg",
    type: "hospitality",
  },
  {
    year: 2016,
    name: "Opal Office, Rome",
    links: "./project.html",
    category: "projects",
    imgSrc: "./media//work-img4.jpg",
    type: "hospitality",
  },
];
